#!/bin/bash
USER_GPG_ID=FB8D294C
DIARYFILE="$HOME/diary.tar"

# Make a temporary initial file
TMPDIARYFILE=`mktemp`

echo "Initial diary entry" > $TMPDIARYFILE
echo `date` >> $TMPDIARYFILE
echo "==============" >> $TMPDIARYFILE

# edit the initial file
vim +4 $TMPDIARYFILE

#encrypt the file when you're done
gpg -r $USER_GPG_ID --batch --encrypt $TMPDIARYFILE
if [ $? ] ; then
    :
else
    echo "Encryption failed, previous file in" $TMPDIARYFILE
    exit -1
fi

shred -u $TMPDIARYFILE

if [ -e $TMPDIARYFILE ]; then
    echo "Shred failed. Sensitive data remaining in " $TMPDIARYFILE
    exit -1
fi

tar -cf $DIARYFILE $TMPDIARYFILE.gpg # append the gpg-encrypted file to a tarchive

shred -u $TMPDIARYFILE.gpg

echo "Diary initialized and recorded."
