#!/bin/bash
DIARYFILE="$HOME/diary.tar"
TMPDIARYFILE=`mktemp`
USER_GPG_ID=FB8D294C

# datestamp the entry for us
echo `date` >> $TMPDIARYFILE
echo "==============" >> $TMPDIARYFILE
#edit the entry
vim +3 $TMPDIARYFILE

# encrypt the new entry
gpg -r $USER_GPG_ID --batch --encrypt $TMPDIARYFILE
if [ $? ] ; then
    :
else
    echo "Encryption failed, previous file in" $TMPDIARYFILE
    exit -1
fi

shred -u $TMPDIARYFILE

if [ -e $TMPDIARYFILE ]; then
    echo "Shred failed. Sensitive data remaining in " $TMPDIARYFILE
    exit -1
fi

tar -rf $DIARYFILE $TMPDIARYFILE.gpg # append the gpg-encrypted file to a tarchive

shred -u $TMPDIARYFILE.gpg

echo "Diary recorded."
